/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
  interface TdtMap {
    center: number[];
    maxBounds: T.MapOptions["maxBounds"];
    maxZoom: T.MapOptions["maxZoom"];
    minZoom: T.MapOptions["minZoom"];
    projection: T.MapOptions["projection"];
    tk: string;
    zoom: T.MapOptions["zoom"];
  }
}
declare global {
  interface HTMLTdtMapElement extends Components.TdtMap, HTMLStencilElement {}
  var HTMLTdtMapElement: {
    prototype: HTMLTdtMapElement;
    new (): HTMLTdtMapElement;
  };
  interface HTMLElementTagNameMap {
    "tdt-map": HTMLTdtMapElement;
  }
}
declare namespace LocalJSX {
  interface TdtMap {
    center?: number[];
    maxBounds: T.MapOptions["maxBounds"];
    maxZoom: T.MapOptions["maxZoom"];
    minZoom: T.MapOptions["minZoom"];
    projection: T.MapOptions["projection"];
    tk: string;
    zoom: T.MapOptions["zoom"];
  }
  interface IntrinsicElements {
    "tdt-map": TdtMap;
  }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      "tdt-map": LocalJSX.TdtMap & JSXBase.HTMLAttributes<HTMLTdtMapElement>;
    }
  }
}
